"""
Event Data Models

Standardized data structures using Pydantic
"""

from typing import List, Optional, Dict, Any
from pydantic import BaseModel
from enum import Enum
from datetime import datetime

class EventType(Enum):
    """Event Type"""
    PROVINCE = "province"  # Province event
    NATIONAL = "national"  # National event

class EffectScope(Enum):
    """Effect Scope"""
    INCOME = "income"           # Income
    EXPENDITURE = "expenditure" # Expenditure
    POPULATION = "population"   # Population
    LOYALTY = "loyalty"         # Loyalty
    STABILITY = "stability"     # Stability
    DEVELOPMENT = "development" # Development

class EffectOperation(Enum):
    """Effect Operation Method"""
    ADD = "add"              # Addition
    MULTIPLY = "multiply"    # Multiplication
    OVERRIDE = "override"    # Override

class EventVisibility(Enum):
    """Event Visibility Level"""
    PUBLIC = "public"              # Fully visible (default for national events)
    PROVINCIAL = "provincial"      # Only visible to the province (default for province events)
    HIDDEN = "hidden"              # Hidden by officials
    CONFIDENTIAL = "confidential"  # Confidential events (only visible to top level)

class AgentEventType(Enum):
    """Agent-generable Event Types"""

    # Finance related
    TAX_ADJUSTMENT = "tax_adjustment"              # Tax adjustment
    BUDGET_REALLOCATION = "budget_reallocation"    # Budget reallocation
    FINANCIAL_SHORTAGE = "financial_shortage"      # Financial shortage

    # Infrastructure
    INFRASTRUCTURE_PROJECT = "infrastructure_project"  # Infrastructure project
    MAINTENANCE_ISSUE = "maintenance_issue"            # Maintenance issue

    # Social events
    PUBLIC_PROTEST = "public_protest"              # Public protest
    SOCIAL_UNREST = "social_unrest"                # Social unrest
    POPULATION_MIGRATION = "population_migration"  # Population migration

    # Natural disasters/accidents
    NATURAL_DISASTER = "natural_disaster"          # Natural disaster
    ACCIDENT = "accident"                          # Accident
    PLAGUE_OUTBREAK = "plague_outbreak"            # Plague outbreak

    # Economic events
    TRADE_DISRUPTION = "trade_disruption"          # Trade disruption
    ECONOMIC_OPPORTUNITY = "economic_opportunity"  # Economic opportunity

    # Political events
    OFFICIAL_INVESTIGATION = "official_investigation"  # Official investigation
    POLITICAL_REFORM = "political_reform"              # Political reform

class EventEffect(BaseModel):
    """Event Effect"""
    scope: EffectScope                      # Effect scope
    operation: EffectOperation              # Operation method
    value: float                            # Effect value
    duration: Optional[int] = None          # Duration (in turns), None means permanent

    class Config:
        use_enum_values = True

class Event(BaseModel):
    """Event Data Model"""
    event_id: str                           # Event ID
    name: str                               # Event name
    description: str                        # Event description
    event_type: EventType                   # Event type
    province_id: Optional[int] = None       # Province ID (required for province events)

    # Effects
    instant_effects: List[EventEffect] = []      # Instant effects
    continuous_effects: List[EventEffect] = []   # Continuous effects

    # Visibility control
    visibility: EventVisibility = EventVisibility.PROVINCIAL  # Default province visibility
    is_hidden_by_governor: bool = False         # Whether hidden by officials
    hidden_reason: Optional[str] = None         # Hidden reason

    # Event metadata
    severity: float = 0.5                       # Severity (0-1)
    public_perception: Optional[str] = None     # Public perception description

    # Authenticity control
    is_agent_generated: bool = False            # Whether generated by Agent
    is_fabricated: bool = False                 # Whether fabricated fake event
    fabrication_reason: Optional[str] = None    # Fabrication reason
    generated_by_agent_id: Optional[str] = None # Generating Agent ID
    narrative_consistency_score: Optional[float] = None  # Narrative consistency score
    verification_status: Optional[str] = None   # Verification status

    # Time attributes
    start_month: int                            # Start turn
    end_month: Optional[int] = None             # End turn (None means permanent)
    is_active: bool = True                      # Whether active
    created_at: datetime = datetime.now()       # Creation time

    def is_expired(self, current_month: int) -> bool:
        """Check if event has expired"""
        if self.end_month is None:
            return False
        return current_month > self.end_month

    def get_remaining_duration(self, current_month: int) -> Optional[int]:
        """Get remaining duration"""
        if self.end_month is None:
            return None
        return max(0, self.end_month - current_month)

    def can_be_seen_by(self, viewer: str) -> bool:
        """
        Determine if event is visible to viewer
        viewer: "central" | "province_<id>"
        """
        if self.visibility == EventVisibility.HIDDEN:
            return False

        if self.visibility == EventVisibility.PUBLIC:
            return True

        if self.visibility == EventVisibility.CONFIDENTIAL:
            # Confidential events only visible to central
            return viewer == "central"

        if self.visibility == EventVisibility.PROVINCIAL:
            # Province events only visible to that province
            if viewer.startswith("province_"):
                viewer_province_id = int(viewer.split("_")[1])
                return viewer_province_id == self.province_id
            return False

        return False

    class Config:
        use_enum_values = True

class AgentEvent(Event):
    """Agent-generated proactive events (inherits from Event)"""

    # Override parent class attributes
    event_type: EventType = EventType.PROVINCE  # Agent events default to province events
    is_agent_generated: bool = True
    generated_by_agent_id: str                 # Agent-generated events must have Agent ID

    # Narrative content
    narrative: str                         # Event description (written by Agent)
    supporting_evidence: Optional[str] = None  # Supporting evidence (when fabricated)

    def verify_consistency(self) -> bool:
        """
        Verify event consistency (used for central detection)
        Check logical consistency between narrative and effects
        """
        if not self.narrative:
            return False

        # Check supporting evidence (if any)
        if self.supporting_evidence and len(self.supporting_evidence) < 10:
            return False

        # Check if effect values are reasonable
        for effect in self.continuous_effects:
            if abs(effect.value) > 2.0:  # Effect values too large may be suspicious
                return False

        return True

    def calculate_consistency_score(self) -> float:
        """
        Calculate narrative consistency score (0-1)
        Used for central Agent to verify event authenticity
        """
        score = 0.5  # Base score

        # Narrative length
        if len(self.narrative) > 50:
            score += 0.1

        # Supporting evidence
        if self.supporting_evidence and len(self.supporting_evidence) > 20:
            score += 0.2

        # Effect reasonableness
        for effect in self.continuous_effects:
            if 0.5 <= abs(effect.value) <= 1.5:
                score += 0.1

        return min(score, 1.0)
